from pathlib import Path

path = Path('tools/import_tuya_local_productless.py')
text = path.read_text()
helper = '''def _prepare_productless_unix_timestamp_sensor(\n    entity: dict[str, Any],\n) -> tuple[dict[str, Any], bool]:\n    """Project Tuya Local ``unixtime`` Sensor values onto explicit runtime support.\n\n    Tuya Local defines ``unixtime`` as integer Unix seconds converted to a\n    datetime.  Only timestamp-class Sensor entities with one untransformed\n    primary sensor DP are accepted; richer shapes remain fail-closed.\n    """\n    if entity.get("entity") != "sensor" or entity.get("class") != "timestamp":\n        return entity, False\n    dps = entity.get("dps")\n    if not isinstance(dps, list):\n        return entity, False\n    sensor_dp = next(\n        (dp for dp in dps if isinstance(dp, dict) and dp.get("name") == "sensor"),\n        None,\n    )\n    if sensor_dp is None or base._dp_type(sensor_dp) != "unixtime":\n        return entity, False\n    if len(dps) != 1 or _raw_mapping(sensor_dp) or sensor_dp.get("precision") is not None:\n        raise ConversionError("sensor_unixtime_semantics")\n    if sensor_dp.get("unit") is not None or sensor_dp.get("class") is not None:\n        raise ConversionError("sensor_unixtime_semantics")\n    transformed = copy.deepcopy(entity)\n    transformed_dp = transformed["dps"][0]\n    transformed_dp["type"] = "integer"\n    return transformed, True\n\n\n'''
anchor = 'def _prepare_runtime_flags(\n'
if text.count(anchor) != 1:
    raise SystemExit(f'Unix sensor helper anchor count={text.count(anchor)}')
text = text.replace(anchor, helper + anchor, 1)
old = '''        climate_limit_precisions: dict[str, float] = {}\n        climate_dynamic_target_range = False\n        typed_select_mapping: dict[str, list[dict[str, Any]]] = {}\n        if platform == "climate":\n'''
new = '''        climate_limit_precisions: dict[str, float] = {}\n        climate_dynamic_target_range = False\n        typed_select_mapping: dict[str, list[dict[str, Any]]] = {}\n        sensor_unix_timestamp = False\n        if platform == "sensor":\n            flagged, sensor_unix_timestamp = _prepare_productless_unix_timestamp_sensor(flagged)\n        elif platform == "climate":\n'''
if text.count(old) != 1:
    raise SystemExit(f'Unix sensor wrapper pre anchor count={text.count(old)}')
text = text.replace(old, new, 1)
old = '''        converted, required, optional = converter(single, *args, **kwargs)\n        if climate_limit_precisions:\n'''
new = '''        converted, required, optional = converter(single, *args, **kwargs)\n        if sensor_unix_timestamp:\n            converted["config"]["sensor_unix_timestamp"] = True\n        if climate_limit_precisions:\n'''
if text.count(old) != 1:
    raise SystemExit(f'Unix sensor wrapper post anchor count={text.count(old)}')
path.write_text(text.replace(old, new, 1))

Path('tests/test_productless_sensor_unix_timestamp.py').write_text('''"""Productless Tuya Local unixtime Sensor regressions."""\n\nimport sys\nimport unittest\nfrom pathlib import Path\n\nsys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))\n\nimport import_tuya_local as base\nimport import_tuya_local_productless as productless\n\n\nconvert_sensor = productless._advanced_wrapper("sensor", base._convert_sensor)\n\n\nclass ProductlessUnixSensorTests(unittest.TestCase):\n    def test_timestamp_unixtime_projects_to_explicit_runtime_flag(self):\n        entity = {\n            "entity": "sensor",\n            "name": "Planting date",\n            "class": "timestamp",\n            "category": "diagnostic",\n            "dps": [{"id": 109, "type": "unixtime", "name": "sensor"}],\n        }\n        converted, required, optional = convert_sensor(entity)\n        self.assertEqual(converted["config"]["id"], 109)\n        self.assertEqual(converted["config"]["device_class"], "timestamp")\n        self.assertIs(converted["config"]["sensor_unix_timestamp"], True)\n        self.assertEqual(required, {109})\n        self.assertEqual(optional, set())\n\n    def test_unixtime_without_timestamp_class_stays_fail_closed(self):\n        entity = {\n            "entity": "sensor",\n            "dps": [{"id": 109, "type": "unixtime", "name": "sensor"}],\n        }\n        with self.assertRaisesRegex(base.ConversionError, "sensor_dp_type"):\n            convert_sensor(entity)\n\n    def test_transformed_unixtime_stays_fail_closed(self):\n        entity = {\n            "entity": "sensor",\n            "class": "timestamp",\n            "dps": [{"id": 109, "type": "unixtime", "name": "sensor", "mapping": [{"scale": 10}]}],\n        }\n        with self.assertRaisesRegex(base.ConversionError, "sensor_unixtime_semantics"):\n            convert_sensor(entity)\n\n\nif __name__ == "__main__":\n    unittest.main()\n''')
