from pathlib import Path

path = Path('tools/import_tuya_local_productless.py')
text = path.read_text(encoding='utf-8')

old = '''    membership_ids = {int(dp_id) for dp_id in advanced_by_dp}\n    for name in referenced_names:\n        dependency = by_name[name]\n        _validate_consumed_dependency(dependency)\n        membership_ids.add(base._dp_id(dependency))\n\n    # Simple LocalTuya entity converters historically require exactly one DP.'''
new = '''    membership_ids = {int(dp_id) for dp_id in advanced_by_dp}\n    for name in referenced_names:\n        dependency = by_name[name]\n        _validate_consumed_dependency(dependency)\n        membership_ids.add(base._dp_id(dependency))\n\n    # Complex platforms may use private redirect/constraint DPS that have no\n    # independent HA-facing meaning (for example Fahrenheit shadow temperature\n    # registers). Keep those DPS in fingerprint/runtime membership, but do not\n    # hand them to the mature platform converter as generic extra attributes.\n    # Named semantic DPS remain visible to the converter even when referenced.\n    if platform == "climate" and referenced_names:\n        climate_semantic_names = {\n            "hvac_mode", "temperature", "current_temperature",\n            "target_temp_low", "target_temp_high", "humidity",\n            "current_humidity", "preset_mode", "fan_mode", "swing_mode",\n            "swing_horizontal_mode", "hvac_action", "temperature_unit",\n            "min_temperature", "max_temperature", "state", "available",\n        }\n        internal_names = referenced_names - climate_semantic_names\n        if internal_names:\n            transformed["dps"] = [\n                dp for dp in transformed.get("dps", [])\n                if not (isinstance(dp, dict) and dp.get("name") in internal_names)\n            ]\n\n    # Simple LocalTuya entity converters historically require exactly one DP.'''
if old not in text:
    raise SystemExit('membership marker missing')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')

test = Path('tests/test_productless_climate_dependencies.py')
test.write_text('''"""Batch N Climate internal advanced dependency tests."""\n\nimport unittest\n\nimport import_tuya_local_productless as productless\n\n\nclass ProductlessClimateDependencyTests(unittest.TestCase):\n    def test_redirect_shadow_dp_is_internal_but_kept_in_membership(self):\n        entity = {\n            "entity": "climate",\n            "dps": [\n                {"id": 1, "name": "hvac_mode", "type": "boolean",\n                 "mapping": [{"dps_val": False, "value": "off"}, {"dps_val": True, "value": "heat"}]},\n                {"id": 2, "name": "temperature", "type": "integer", "range": {"min": 16, "max": 30},\n                 "mapping": [{"constraint": "temperature_unit", "conditions": [\n                     {"dps_val": "fahrenheit", "value_redirect": "temperature_f"}\n                 ]}]},\n                {"id": 19, "name": "temperature_unit", "type": "string",\n                 "mapping": [{"dps_val": "c", "value": "celsius"}, {"dps_val": "f", "value": "fahrenheit"}]},\n                {"id": 20, "name": "temperature_f", "type": "integer", "range": {"min": 60, "max": 104}},\n            ],\n        }\n        prepared, advanced, membership = productless._prepare_advanced_entity(entity, "climate")\n        self.assertEqual({dp["name"] for dp in prepared["dps"]}, {"hvac_mode", "temperature", "temperature_unit"})\n        self.assertIn(20, membership)\n        self.assertEqual(advanced["2"][0]["conditions"][0]["value_redirect_dp"], 20)\n\n    def test_semantic_constraint_dp_is_not_stripped(self):\n        entity = {\n            "entity": "climate",\n            "dps": [\n                {"id": 2, "name": "temperature", "type": "integer", "range": {"min": 16, "max": 30},\n                 "mapping": [{"constraint": "temperature_unit", "conditions": [{"dps_val": "fahrenheit", "step": 1}]}]},\n                {"id": 19, "name": "temperature_unit", "type": "string",\n                 "mapping": [{"dps_val": "c", "value": "celsius"}, {"dps_val": "f", "value": "fahrenheit"}]},\n            ],\n        }\n        prepared, _, _ = productless._prepare_advanced_entity(entity, "climate")\n        self.assertIn("temperature_unit", {dp["name"] for dp in prepared["dps"]})\n\n\nif __name__ == "__main__":\n    unittest.main()\n''', encoding='utf-8')
