from pathlib import Path

p = Path("tools/import_tuya_local_productless.py")
text = p.read_text(encoding="utf-8")

old = '''    def needs_advanced(name: Any, rule: dict[str, Any]) -> bool:\n        if set(rule) & (_ADVANCED_SOURCE_KEYS | _UNSUPPORTED_ADVANCED_KEYS):\n            return True\n        # Tuya Local hidden mappings still participate in forward/read mapping\n        # but are excluded from value lists and reverse writes. LocalTuya's\n        # advanced mapper has the same semantics. Batch N enables this only for\n        # Climate swing enums where hidden rules are forward-only fallbacks.\n        return (\n            platform == "climate"\n            and name in {"swing_mode", "swing_horizontal_mode"}\n            and rule.get("hidden") is True\n        )\n\n    has_advanced = False\n    for raw_dp in raw_dps:\n        if not isinstance(raw_dp, dict):\n            continue\n        name = raw_dp.get("name")\n        for rule in _raw_mapping(raw_dp):\n            if needs_advanced(name, rule):\n                has_advanced = True\n                break\n        if has_advanced:\n            break\n'''
new = '''    def needs_advanced(name: Any, rule: dict[str, Any]) -> bool:\n        if set(rule) & (_ADVANCED_SOURCE_KEYS | _UNSUPPORTED_ADVANCED_KEYS):\n            return True\n        # Tuya Local hidden mappings still participate in forward/read mapping\n        # but are excluded from value lists and reverse writes. LocalTuya's\n        # advanced mapper has the same semantics. Batch N enables this only for\n        # Climate swing enums where hidden rules are forward-only fallbacks.\n        return (\n            platform == "climate"\n            and name in {"swing_mode", "swing_horizontal_mode"}\n            and rule.get("hidden") is True\n        )\n\n    def dp_needs_advanced(name: Any, rules: list[dict[str, Any]]) -> bool:\n        if any(needs_advanced(name, rule) for rule in rules):\n            return True\n        if platform != "climate" or name != "hvac_action" or len(rules) < 2:\n            return False\n        # Read-only HVAC action can legitimately be many-to-one (several raw\n        # device states collapse to heating/idle). The mature converter stores\n        # friendly->raw and therefore cannot represent that losslessly. Route\n        # only fully explicit, non-null static mappings through the per-DP\n        # advanced mapper, while keeping null/default fallbacks fail-closed.\n        values: list[Any] = []\n        for rule in rules:\n            if set(rule) - {"dps_val", "value"}:\n                return False\n            if "dps_val" not in rule or rule.get("dps_val") is None or "value" not in rule:\n                return False\n            value = rule.get("value")\n            if not isinstance(value, str) or not value:\n                return False\n            values.append(value)\n        return len(set(values)) < len(values)\n\n    has_advanced = False\n    for raw_dp in raw_dps:\n        if not isinstance(raw_dp, dict):\n            continue\n        name = raw_dp.get("name")\n        if dp_needs_advanced(name, _raw_mapping(raw_dp)):\n            has_advanced = True\n            break\n'''
if new not in text:
    if old not in text:
        raise SystemExit("advanced trigger anchor missing")
    text = text.replace(old, new, 1)

old2 = '''        rules = _raw_mapping(original_dp)\n        if not any(needs_advanced(name, rule) for rule in rules):\n            continue\n'''
new2 = '''        rules = _raw_mapping(original_dp)\n        if not dp_needs_advanced(name, rules):\n            continue\n'''
if new2 not in text:
    if old2 not in text:
        raise SystemExit("per-DP trigger anchor missing")
    text = text.replace(old2, new2, 1)

p.write_text(text, encoding="utf-8")

t = Path("tests/test_productless_climate_hvac_action.py")
if not t.exists():
    t.write_text('''"""Batch N Climate HVAC action many-to-one mapping tests."""\n\nimport unittest\n\nimport import_tuya_local_productless as productless\n\n\nclass ProductlessClimateHvacActionTests(unittest.TestCase):\n    def test_explicit_many_to_one_action_uses_advanced_mapping(self):\n        entity = {\n            "entity": "climate",\n            "dps": [\n                {\n                    "id": 1, "name": "hvac_mode", "type": "boolean",\n                    "mapping": [\n                        {"dps_val": False, "value": "off"},\n                        {"dps_val": True, "value": "heat"},\n                    ],\n                },\n                {\n                    "id": 104, "name": "hvac_action", "type": "string", "readonly": True,\n                    "mapping": [\n                        {"dps_val": "heating", "value": "heating"},\n                        {"dps_val": "warm", "value": "heating"},\n                        {"dps_val": "stop", "value": "idle"},\n                        {"dps_val": "standby", "value": "idle"},\n                    ],\n                },\n            ],\n        }\n        prepared, advanced, membership = productless._prepare_advanced_entity(entity, "climate")\n        self.assertEqual(\n            advanced["104"],\n            [\n                {"dps_val": "heating", "value": "heating"},\n                {"dps_val": "warm", "value": "heating"},\n                {"dps_val": "stop", "value": "idle"},\n                {"dps_val": "standby", "value": "idle"},\n            ],\n        )\n        action = next(dp for dp in prepared["dps"] if dp["name"] == "hvac_action")\n        self.assertEqual(\n            action["mapping"],\n            [\n                {"dps_val": "heating", "value": "heating"},\n                {"dps_val": "idle", "value": "idle"},\n            ],\n        )\n        self.assertIn(104, membership)\n\n    def test_null_fallback_action_remains_fail_closed(self):\n        entity = {\n            "entity": "climate",\n            "dps": [{\n                "id": 7, "name": "hvac_action", "type": "boolean", "readonly": True,\n                "mapping": [\n                    {"dps_val": False, "value": "idle"},\n                    {"dps_val": True, "value": "heating"},\n                    {"dps_val": None, "value": "idle"},\n                ],\n            }],\n        }\n        prepared, advanced, membership = productless._prepare_advanced_entity(entity, "climate")\n        self.assertEqual(advanced, {})\n        self.assertEqual(membership, set())\n        self.assertEqual(prepared, entity)\n\n\nif __name__ == "__main__":\n    unittest.main()\n''', encoding="utf-8")
