from pathlib import Path

path = Path("tests/test_import_tuya_local_productless.py")
text = path.read_text(encoding="utf-8")
old = '''    def test_multidp_extra_mapping_stays_fail_closed(self):\n        with self.assertRaisesRegex(ConversionError, "sensor_extra_mapping:description"):\n            self._convert([\n                {\n                    "entity": "sensor",\n                    "dps": [\n                        {"id": 1, "name": "sensor", "type": "integer"},\n                        {\n                            "id": 2,\n                            "name": "description",\n                            "type": "string",\n                            "mapping": [{"dps_val": "x", "value": "friendly"}],\n                        },\n                    ],\n                }\n            ])\n'''
new = '''    def test_multidp_safe_extra_mapping_uses_mapped_attribute_channel(self):\n        result = self._convert([\n            {\n                "entity": "sensor",\n                "dps": [\n                    {"id": 1, "name": "sensor", "type": "integer"},\n                    {\n                        "id": 2,\n                        "name": "description",\n                        "type": "string",\n                        "mapping": [{"dps_val": "x", "value": "friendly"}],\n                    },\n                ],\n            }\n        ])\n        config = result["entities"][0]["config"]\n        self.assertEqual(config["mapped_extra_state_attributes_dps"], {"description": 2})\n        self.assertEqual(\n            config["advanced_mapping_by_dp"]["2"],\n            [{"dps_val": "x", "value": "friendly"}],\n        )\n\n    def test_multidp_richer_extra_mapping_stays_fail_closed(self):\n        with self.assertRaisesRegex(ConversionError, "multi_dp_mapped_extra:description"):\n            self._convert([\n                {\n                    "entity": "sensor",\n                    "dps": [\n                        {"id": 1, "name": "sensor", "type": "integer"},\n                        {\n                            "id": 2,\n                            "name": "description",\n                            "type": "integer",\n                            "mapping": [{"scale": 10, "step": 1}],\n                        },\n                    ],\n                }\n            ])\n'''
if new in text:
    raise SystemExit(0)
if old not in text:
    raise SystemExit("expected legacy mapped-extra test not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
